export { default as Title } from './Bachelor/Title/';
export { default as Decan } from './Bachelor/Decan/';
export { default as Spesh } from './Bachelor/Spesh/';
export { default as Spisok } from './Bachelor/Spisok';
export { default as News } from './Bachelor/News';
export { default as Gide } from './Bachelor/Gide';
export { default as Dostish } from './Bachelor/Dostish';
export { default as Nomber } from './Bachelor/Nomber';
export { default as Obed } from './Bachelor/Obed';
export { default as End } from './Bachelor/End';
export { default as Footer } from './Bachelor/Footer';
export { default as Header } from './Bachelor/Header';
export { default as MagHeader } from './Magistracy/magHeader';
export { default as MagTitle } from './Magistracy/magTitle';
export { default as MagSpesh } from './Magistracy/magSpesh';
export { default as MagEntrance } from './Magistracy/magEntrance';
export { default as HeaderD } from './Directions/HeaderD';
export { default as TitleD } from './Directions/TitleD';
export { default as DescriptionD } from './Directions/DescriptionD';
export { default as FormaD } from './Directions/FormaD';
export { default as ProfileD} from './Directions/ProfileD';
export { default as PossibilityD} from './Directions/PossibilityD';
export { default as DepartmentD} from './Directions/DepartmentD';
export { default as EntranceD} from './Directions/EntranceD';
export { default as NomberD} from './Directions/NomberD';
export { default as TitleEcoD} from './econDirections/TitleEcoD';
export { default as TitleMangD} from './mangDirections/TitleMangD';
export { default as TitleTradD} from './tradDirections03/TitleTradD';
export { default as TitleTradeD} from './tradDirections04/TitleTradeD';
export { default as TitleFinD} from './finDirections/TitleFinD';